apiVersion: v1
kind: Pod
metadata:
  name: yellow
  labels:
    app: db
    tier: backend

spec:
  containers:
  - name: lemon
    image:  busybox
    command: ["sleep"]
    args: ["300"]
  - name: gold
    image: redis