apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
  labels:
    app: nginx-webserver

spec:
  containers:
  - name: nginx
    image: nginx:alpine
    envFrom:
    - configMapRef:
        name: webapp-config-map