apiVersion: apps/v1
kind: Deployment
metadata: 
  name: beta
  namespace: finance
  labels:
    app: redis-app
    type: DB
  

spec:
  replicas: 2
  selector:
    matchLabels:
      type: DB

  template:
    metadata:
      name: redis-pod
      labels:
        app: redis-app
        type: DB

    spec:
      containers:
      - name: beta
        image: redis
        resources:
          requests:
            cpu: ".5"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"