apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  namespace: kube-system
  labels:
    app: fluentd

spec:
  selector:
    matchLabels:
      app: fluentd-logging

  template:
    metadata:
      name: fluentd-pod
      labels:
        app: fluentd-logging

    spec:

      containers:
        - name : elasticsearch
          image: k8s.gcr.io/fluentd-elasticsearch:1.20

          resources:
            limits:
              memory : "1Gi"
              cpu: "2"
            requests:
              memory : "200Mi"
              cpu: ".5"