apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: web-app

spec:
  type: NodePort
  ports:
    - targetPort : 80
      port: 80
      nodePort: 30003

  selector:
    app: web-app