apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app

  template:
    metadata:
      name: web-app-pod
      labels:
        app: web-app

    spec:
      containers:
         - name: nginx1
           image: nginx